#!/bin/sh
exec 2>&1
exec env \
    HOME="/home/rien"                               \
    PATH="/usr/local/bin:$HOME/.local/bin:$PATH"    \
    DISPLAY=":0"                                    \
    xautolock -time 5 -locker lockscreen -notify 5
