#!/bin/sh
exec 2>&1
exec env                                        \
    HOME="/home/rien"                           \
    PATH="/home/rien/.local/bin:$PATH"          \
    DISPLAY=":0"                                \
    bar
